title: NovaTrace OSINT Blog
email: your.email@example.com
description: >-
  Documenting OSINT investigations, scam breakdowns, and cyber threat research.

baseurl: "" # leave this empty for user GitHub Pages
url: "https://novatraceosint.github.io" # your site URL

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "neon"

plugins:
  - jekyll-include-cache

# Build settings
markdown: kramdown
theme: null

# Author info (used in sidebar and footer)
author:
  name: "Romer Tanaleon"
  avatar: "/assets/images/NovaTrace_Shield.png" # optional profile picture
  bio: "OSINT investigator | NovaTrace"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/novatraceosint"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/romer-tanaleon"


# Enable UI features
search: true
breadcrumbs: true
show_date: true

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
